export const products = [
  {
    id: "p1",
    name: "Classic Black Hoodie",
    slug: "classic-black-hoodie",
    description: "A cozy, comfortable black hoodie made from premium cotton.",
    category: "Men",
    subcategory: "Hoodies",
    price: 3000,

    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray"],
    mainImage: "/banner1.jpg",
    secondaryImages: ["/banner2.jpg", "/banner3.jpg"],
    stock: { S: 10, M: 5, L: 0, XL: 3 },
    material: "100% Cotton",
    brand: "UrbanStyle",
    rating: 4.6,
    numReviews: 38,
    isFeatured: true,
    tags: ["hoodie", "winter", "cotton", "urban"],
    createdAt: "2025-06-27T10:00:00Z",
    updatedAt: "2025-06-27T12:00:00Z"
  },
  {
    id: "p2",
    name: "Urban Blue Jeans",
    slug: "urban-blue-jeans",
    description: "Trendy blue jeans for everyday wear.",
    category: "Men",
    subcategory: "Jeans",
    price: 3500,
    discountPrice: 3200,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black"],
    mainImage: "/banner2.jpg",
    secondaryImages: ["/banner1.jpg", "/banner3.jpg"],
    stock: { S: 8, M: 6, L: 2, XL: 4 },
    material: "Denim",
    brand: "UrbanStyle",
    rating: 4.7,
    numReviews: 22,
    isFeatured: false,
    tags: ["jeans", "denim", "urban"],
    createdAt: "2025-06-27T10:10:00Z",
    updatedAt: "2025-06-27T12:10:00Z"
  },
  {
    id: "p3",
    name: "White Cotton T-Shirt",
    slug: "white-cotton-tshirt",
    description: "A premium white t-shirt for a clean, classic look.",
    category: "Men",
    subcategory: "T-Shirts",
    price: 1200,
    discountPrice: 1000,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White"],
    mainImage: "/banner3.jpg",
    secondaryImages: ["/banner2.jpg", "/banner4.jpg"],
    stock: { S: 7, M: 3, L: 1, XL: 2 },
    material: "100% Cotton",
    brand: "UrbanStyle",
    rating: 4.8,
    numReviews: 15,
    isFeatured: true,
    tags: ["tshirt", "white", "cotton"],
    createdAt: "2025-06-27T10:20:00Z",
    updatedAt: "2025-06-27T12:20:00Z"
  },
  {
    id: "p4",
    name: "Slim Fit Jacket",
    slug: "slim-fit-jacket",
    description: "A stylish slim fit jacket for cool evenings.",
    category: "Men",
    subcategory: "Jackets",
    price: 4200,
    discountPrice: 3900,
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Navy"],
    mainImage: "/banner4.jpg",
    secondaryImages: ["/banner3.jpg", "/banner5.jpg"],
    stock: { M: 9, L: 4, XL: 2 },
    material: "Polyester",
    brand: "UrbanStyle",
    rating: 4.5,
    numReviews: 18,
    isFeatured: false,
    tags: ["jacket", "slim", "fit"],
    createdAt: "2025-06-27T10:30:00Z",
    updatedAt: "2025-06-27T12:30:00Z"
  },
  {
    id: "p5",
    name: "Summer Shorts",
    slug: "summer-shorts",
    description: "Lightweight shorts perfect for summer.",
    category: "Men",
    subcategory: "Shorts",
    price: 1800,

    sizes: ["S", "M", "L"],
    colors: ["Beige", "Blue"],
    mainImage: "/banner5.jpg",
    secondaryImages: ["/banner4.jpg", "/banner6.jpg"],
    stock: { S: 5, M: 2, L: 0 },
    material: "Cotton",
    brand: "UrbanStyle",
    rating: 4.9,
    numReviews: 25,
    isFeatured: true,
    tags: ["shorts", "summer", "cotton"],
    createdAt: "2025-06-27T10:40:00Z",
    updatedAt: "2025-06-27T12:40:00Z"
  },
  {
    id: "p6",
    name: "Floral Summer Dress",
    slug: "floral-summer-dress",
    description: "A beautiful floral dress for summer days.",
    category: "Women",
    subcategory: "Dresses",
    price: 3200,
    discountPrice: 2800,
    sizes: ["S", "M", "L"],
    colors: ["Pink", "White"],
    mainImage: "/banner6.jpg",
    secondaryImages: ["/banner5.jpg", "/banner7.jpg"],
    stock: { S: 6, M: 3, L: 1 },
    material: "Rayon",
    brand: "UrbanStyle",
    rating: 4.7,
    numReviews: 19,
    isFeatured: true,
    tags: ["dress", "floral", "summer"],
    createdAt: "2025-06-27T10:50:00Z",
    updatedAt: "2025-06-27T12:50:00Z"
  },
  {
    id: "p7",
    name: "High Waist Jeans",
    slug: "high-waist-jeans",
    description: "Trendy high waist jeans for a modern look.",
    category: "Women",
    subcategory: "Jeans",
    price: 3400,
    discountPrice: 3000,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue"],
    mainImage: "/banner7.jpg",
    secondaryImages: ["/banner6.jpg", "/banner8.jpg"],
    stock: { S: 4, M: 2, L: 2, XL: 1 },
    material: "Denim",
    brand: "UrbanStyle",
    rating: 4.6,
    numReviews: 21,
    isFeatured: false,
    tags: ["jeans", "highwaist", "trendy"],
    createdAt: "2025-06-27T11:00:00Z",
    updatedAt: "2025-06-27T13:00:00Z"
  },
  {
    id: "p8",
    name: "Pink Hoodie",
    slug: "pink-hoodie",
    description: "Soft and cozy pink hoodie for chilly days.",
    category: "Women",
    subcategory: "Hoodies",
    price: 3100,
    discountPrice: 2700,
    sizes: ["S", "M", "L"],
    colors: ["Pink"],
    mainImage: "/banner8.jpg",
    secondaryImages: ["/banner7.jpg", "/banner1.jpg"],
    stock: { S: 5, M: 2, L: 0 },
    material: "Fleece",
    brand: "UrbanStyle",
    rating: 4.8,
    numReviews: 25,
    isFeatured: true,
    tags: ["hoodie", "pink", "cozy"],
    createdAt: "2025-06-27T11:10:00Z",
    updatedAt: "2025-06-27T13:10:00Z"
  },
  {
    id: "p9",
    name: "Classic White T-Shirt",
    slug: "classic-white-tshirt",
    description: "A classic white t-shirt for any occasion.",
    category: "Women",
    subcategory: "T-Shirts",
    price: 1100,
    discountPrice: 900,
    sizes: ["S", "M", "L"],
    colors: ["White"],
    mainImage: "/banner1.jpg",
    secondaryImages: ["/banner8.jpg", "/banner2.jpg"],
    stock: { S: 6, M: 4, L: 2 },
    material: "Cotton",
    brand: "UrbanStyle",
    rating: 4.2,
    numReviews: 10,
    isFeatured: false,
    tags: ["tshirt", "white", "classic"],
    createdAt: "2025-06-27T11:20:00Z",
    updatedAt: "2025-06-27T13:20:00Z"
  },
  {
    id: "p10",
    name: "Pleated Skirt",
    slug: "pleated-skirt",
    description: "A stylish pleated skirt for a chic look.",
    category: "Women",
    subcategory: "Skirts",
    price: 2100,
    discountPrice: 1800,
    sizes: ["S", "M", "L"],
    colors: ["Beige", "Black"],
    mainImage: "/banner2.jpg",
    secondaryImages: ["/banner1.jpg", "/banner3.jpg"],
    stock: { S: 3, M: 2, L: 1 },
    material: "Polyester",
    brand: "UrbanStyle",
    rating: 4.5,
    numReviews: 17,
    isFeatured: false,
    tags: ["skirt", "pleated", "chic"],
    createdAt: "2025-06-27T11:30:00Z",
    updatedAt: "2025-06-27T13:30:00Z"
  },
  {
    id: "p11",
    name: "Oversized Hoodie",
    slug: "oversized-hoodie",
    description: "Trendy oversized hoodie for a relaxed fit.",
    category: "Unisex",
    subcategory: "Hoodies",
    price: 3300,
    discountPrice: 2900,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray"],
    mainImage: "/banner3.jpg",
    secondaryImages: ["/banner2.jpg", "/banner4.jpg"],
    stock: { S: 8, M: 6, L: 2, XL: 4 },
    material: "Cotton",
    brand: "UrbanStyle",
    rating: 4.7,
    numReviews: 22,
    isFeatured: false,
    tags: ["hoodie", "oversized", "relaxed"],
    createdAt: "2025-06-27T11:40:00Z",
    updatedAt: "2025-06-27T13:40:00Z"
  },
  {
    id: "p12",
    name: "Graphic T-Shirt",
    slug: "graphic-tshirt",
    description: "A cool graphic t-shirt for everyday style.",
    category: "Unisex",
    subcategory: "T-Shirts",
    price: 1500,
    discountPrice: 1200,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black"],
    mainImage: "/banner4.jpg",
    secondaryImages: ["/banner3.jpg", "/banner5.jpg"],
    stock: { S: 7, M: 3, L: 1, XL: 2 },
    material: "Cotton",
    brand: "UrbanStyle",
    rating: 4.8,
    numReviews: 15,
    isFeatured: true,
    tags: ["tshirt", "graphic", "cool"],
    createdAt: "2025-06-27T11:50:00Z",
    updatedAt: "2025-06-27T13:50:00Z"
  },
  {
    id: "p13",
    name: "Denim Jacket",
    slug: "denim-jacket-unisex",
    description: "A classic denim jacket for all seasons.",
    category: "Unisex",
    subcategory: "Jackets",
    price: 4000,
    discountPrice: 3700,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue"],
    mainImage: "/banner5.jpg",
    secondaryImages: ["/banner4.jpg", "/banner6.jpg"],
    stock: { S: 6, M: 3, L: 1, XL: 2 },
    material: "Denim",
    brand: "UrbanStyle",
    rating: 4.6,
    numReviews: 21,
    isFeatured: false,
    tags: ["jacket", "denim", "classic"],
    createdAt: "2025-06-27T12:00:00Z",
    updatedAt: "2025-06-27T14:00:00Z"
  },
  {
    id: "p14",
    name: "Casual Shorts",
    slug: "casual-shorts-unisex",
    description: "Comfortable shorts for casual outings.",
    category: "Unisex",
    subcategory: "Shorts",
    price: 1700,
    discountPrice: 1400,
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Blue"],
    mainImage: "/banner6.jpg",
    secondaryImages: ["/banner5.jpg", "/banner7.jpg"],
    stock: { S: 5, M: 2, L: 0 },
    material: "Cotton",
    brand: "UrbanStyle",
    rating: 4.9,
    numReviews: 25,
    isFeatured: true,
    tags: ["shorts", "casual", "cotton"],
    createdAt: "2025-06-27T12:10:00Z",
    updatedAt: "2025-06-27T14:10:00Z"
  },
  {
    id: "p15",
    name: "Basic Sweatpants",
    slug: "basic-sweatpants-unisex",
    description: "Basic sweatpants for everyday comfort.",
    category: "Unisex",
    subcategory: "Sweatpants",
    price: 2200,
    discountPrice: 1900,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray"],
    mainImage: "/banner7.jpg",
    secondaryImages: ["/banner6.jpg", "/banner8.jpg"],
    stock: { S: 4, M: 2, L: 2, XL: 1 },
    material: "Cotton",
    brand: "UrbanStyle",
    rating: 4.6,
    numReviews: 21,
    isFeatured: false,
    tags: ["sweatpants", "basic", "cotton"],
    createdAt: "2025-06-27T12:20:00Z",
    updatedAt: "2025-06-27T14:20:00Z"
  },
  {
    id: "p16",
    name: "Winter Sweater",
    slug: "winter-sweater-men",
    description: "A warm sweater for cold winter days.",
    category: "Men",
    subcategory: "Sweaters",
    price: 2800,
    discountPrice: 2500,
    sizes: ["M", "L", "XL"],
    colors: ["Gray", "Navy"],
    mainImage: "/banner8.jpg",
    secondaryImages: ["/banner7.jpg", "/banner1.jpg"],
    stock: { M: 6, L: 3, XL: 1 },
    material: "Wool Blend",
    brand: "UrbanStyle",
    rating: 4.3,
    numReviews: 12,
    isFeatured: false,
    tags: ["sweater", "winter", "warm"],
    createdAt: "2025-06-27T12:30:00Z",
    updatedAt: "2025-06-27T14:30:00Z"
  },
  {
    id: "p17",
    name: "Formal Shirt",
    slug: "formal-shirt-men",
    description: "A crisp formal shirt for office or events.",
    category: "Men",
    subcategory: "Shirts",
    price: 2600,
    discountPrice: 2300,
    sizes: ["M", "L", "XL"],
    colors: ["White", "Blue"],
    mainImage: "/banner1.jpg",
    secondaryImages: ["/banner8.jpg", "/banner2.jpg"],
    stock: { M: 5, L: 2, XL: 1 },
    material: "Cotton",
    brand: "UrbanStyle",
    rating: 4.7,
    numReviews: 16,
    isFeatured: false,
    tags: ["shirt", "formal", "office"],
    createdAt: "2025-06-27T12:40:00Z",
    updatedAt: "2025-06-27T14:40:00Z"
  },
  {
    id: "p18",
    name: "Denim Jacket",
    slug: "denim-jacket-women",
    description: "A stylish denim jacket for women.",
    category: "Women",
    subcategory: "Jackets",
    price: 3900,
    discountPrice: 3500,
    sizes: ["S", "M", "L"],
    colors: ["Blue"],
    mainImage: "/banner2.jpg",
    secondaryImages: ["/banner1.jpg", "/banner3.jpg"],
    stock: { S: 3, M: 2, L: 1 },
    material: "Denim",
    brand: "UrbanStyle",
    rating: 4.5,
    numReviews: 17,
    isFeatured: false,
    tags: ["jacket", "denim", "women"],
    createdAt: "2025-06-27T12:50:00Z",
    updatedAt: "2025-06-27T14:50:00Z"
  },
  {
    id: "p19",
    name: "Comfy Sweatpants",
    slug: "comfy-sweatpants-women",
    description: "Comfy sweatpants for lounging or workouts.",
    category: "Women",
    subcategory: "Sweatpants",
    price: 2000,
    discountPrice: 1700,
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Black"],
    mainImage: "/banner3.jpg",
    secondaryImages: ["/banner2.jpg", "/banner4.jpg"],
    stock: { S: 3, M: 2, L: 1 },
    material: "Cotton",
    brand: "UrbanStyle",
    rating: 4.7,
    numReviews: 12,
    isFeatured: false,
    tags: ["sweatpants", "comfy", "women"],
    createdAt: "2025-06-27T13:00:00Z",
    updatedAt: "2025-06-27T15:00:00Z"
  },
  {
    id: "p20",
    name: "Lightweight Windbreaker",
    slug: "lightweight-windbreaker-unisex",
    description: "A lightweight windbreaker for all weather.",
    category: "Unisex",
    subcategory: "Jackets",
    price: 3500,
    discountPrice: 3200,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "Black"],
    mainImage: "/banner4.jpg",
    secondaryImages: ["/banner3.jpg", "/banner5.jpg"],
    stock: { S: 4, M: 2, L: 1, XL: 1 },
    material: "Polyester",
    brand: "UrbanStyle",
    rating: 4.8,
    numReviews: 8,
    isFeatured: true,
    tags: ["windbreaker", "lightweight", "unisex"],
    createdAt: "2025-06-27T13:10:00Z",
    updatedAt: "2025-06-27T15:10:00Z"
  }
];